// Pins the JDK Gradle runs on to 17 via Gradle's daemon-JVM criteria file, so Android Studio and
// CI agree and JDK 24+ never gets picked up. JDK 24+ emits "WARNING: A restricted method in
// java.lang.System has been called" when prefab loads native code, and AGP treats any stderr from
// prefab as a build failure. Written after prebuild so it survives regeneration of android/.
const { withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

module.exports = function withGradleDaemonJvm(config, { version = 17 } = {}) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, "gradle");
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(
        path.join(dir, "gradle-daemon-jvm.properties"),
        `#This file is generated by expo prebuild (plugins/withGradleDaemonJvm.js)\ntoolchainVersion=${version}\n`,
      );
      return cfg;
    },
  ]);
};
